### ISSUE TITLE
Allow marking ParameterDefinition as secrets / not to be captured by cliopatra

### ISSUE THREAD

**Issue by wesen** [go-go-golems/glazed#241]
For example, what should we do about this:

```
❯ sqleton ttc orders orders --from 2023-01-01 --create-cliopatra
name: sqleton
verbs:
    - ttc
    - orders
    - orders
description: Show WooCommerce orders.
flags:
    - name: host
      short: Database host
      type: string
      value: localhost
    - name: user
      short: Database user
      type: string
      value: root
    - name: schema
      short: Database schema (when applicable)
      type: string
      value: ttc_analytics
    - name: database
      short: Database name
      type: string
      value: ttc_analytics
    - name: password
      short: Database password
      type: string
      value: somewordpress
    - name: port
      short: Database port
      type: int
      value: 3336
    - name: use-dbt-profiles
      short: Use dbt profiles.yml file
      type: bool
      value: true
      noValue: true
    - name: dbt-profile
      short: dbt profile to use
      type: string
      value: localhost.ttc
    - name: from
      short: From date
      type: date
      value: 2023-01-01T00:00:00Z

```
