### ISSUE TITLE
Add a way to quickly add alias functionality to a tool using glazed

### ISSUE THREAD

**Issue by wesen** [go-go-golems/glazed#268]
For example, it would be cool to have harkonnen use something like:

```
name: quick-api-exporter
aliasFor: har
flags:
    match-urls: .*-api/.*
    output: yaml
    with-request-headers: "false"
    with-response: "true"
    with-response-body: "true"
    with-response-headers: "false"
```

instead of having to type `harkonnen har ~/Downloads/openai.har --match-urls '.*-api/.*' --output yaml --with-request-headers=false --with-response --with-response-body --with-response-headers=false`
